### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by developer239** [BondGoat/react-native-native-video-player#11]
Thank you so much for this library. :)

**Comment by developer239** [comment]
However this: `Edit the path variable from $(SRCROOT)/../../../HuntersLog to $(SRCROOT)/../../../[YOUR PROJECT FOLDER NAME]` is re******. :( :( Changing anything in node_modules is wrong.

**Comment by AnisDerbel** [comment]
This library save my life!! thanks a lot
