### ISSUE TITLE
Not a component, but an external launcher on Android?

### ISSUE THREAD

**Issue by Noitidart** [BondGoat/react-native-native-video-player#20]
I tested this on Android, and when I say to play video it prompts to play in an external app. Screenshot below. Is this correct? I thought this was a native android video player component that I could inlay within my app?

![screenshot_2018-02-28-13-33-24](https://user-images.githubusercontent.com/6372489/36814347-19f6628c-1c8c-11e8-951b-9b122fa5db92.png)

**Comment by salimbutex** [comment]
same issues. this is so stupid...
