### ISSUE TITLE
AppDelegate.h file not found

### ISSUE THREAD

**Issue by addu1** [BondGoat/react-native-native-video-player#26]
My project contains pod files. So once i install the pods i start getting this error.

![screen shot 2018-08-24 at 12 04 20 pm](https://user-images.githubusercontent.com/17162834/44568882-25729780-a796-11e8-9e4d-4638dcc9a163.png)

**Comment by addu1** [comment]
@BondGoat

**Comment by ericmgoeken** [comment]
Seems odd for a library to reference AppDelegate.h not to mention that if you have a swift based app then you have a AppDelegate.swift

**Comment by chengsam** [comment]
#4

**Comment by ericmgoeken** [comment]
@chengsam, Thanks for pulling up #4. I think that would help most, but my project does not use an AppDelegate.h it is all swift so I have an AppDelegate.swift. 

I created a pull request to remove the cast to AppDelegate and no longer use the AppDelegate.h reference. It is really just a copy job from [a-voityuk's fork](https://github.com/a-voityuk/react-native-native-video-player)
