### ISSUE TITLE
AppDelegate.h' file not found

### ISSUE THREAD

**Issue by arshavinho** [BondGoat/react-native-native-video-player#3]
hello,

i was trying your video player and this error shows up:
```.../node_modules/react-native-native-video-player/ios/RNVideoPlayer/RNVideoPlayer.h:9:9: 'AppDelegate.h' file not found```

Do you know why ?
Thanks

**Comment by Secretmapper** [comment]
Any info how you got this to work @arshavinho ?

**Comment by BondGoat** [comment]
Hi,

The AppDelegate.h is imported from the root ios project.
Please add this : $(SRCROOT)/../../../ios/[your project name] to the RNVideoPlayer - Header Search Paths, and set 'recursive'

Let me know there're any problems.

**Comment by rf1804** [comment]
@BondGoat I have changed the header search path but still it is giving me the error of AppDelegate.h not found

**Comment by amed** [comment]
`react-native@0.55.4`
`react-native-native-video-player@^1.3.4`

It seems that this issue is not going to be solved easily. Same here, `AppDelegate.h` file not found.

**Comment by rohit75** [comment]
/node_modules/react-native-native-video-player/ios/RNVideoPlayer/RNVideoPlayer.h:9:9: fatal error: 'AppDelegate.h' file not found
#import "AppDelegate.h
               ^~~~~~~~~~~~~~~

Not able to build on IOS. Any solutions?

**Comment by sweshgit** [comment]
I could solve this issue by following simply adding Header Search Path.

Adding your project path in Header Search path will solve the problem as below for the particular POD imports.
So whichever module, you are importing, please add the Header Search Path for the same as below.

"${PODS_ROOT}/../Your Project Name"

![image](https://user-images.githubusercontent.com/14069245/80315145-5fb9f500-8813-11ea-9a11-a0ae44a39ee1.png)
