### ISSUE TITLE
Need license information for this module

### ISSUE THREAD

**Issue by PradeepNedun** [BondGoat/react-native-native-video-player#34]
Hi,

Can you please let me know the license information for this module.
Package.json says that it is "WOG".
Is it MIT or some other license?

**Comment by PradeepNedun** [comment]
Please let us know the license information.

**Comment by BondGoat** [comment]
Hi @PradeepNedun ,

This module is open source, I did it for personal usage.
Feel free to get and modify.

Thanks.

**Comment by PradeepNedun** [comment]
Hi @BondGoat ,

Thank you for the quick response.
Can you please update the license info or add a LICENSE file to the project

Thanks
