### ISSUE TITLE
Xcode compile error

### ISSUE THREAD

**Issue by hoseinmobasher** [BondGoat/react-native-native-video-player#4]
Hello,
I've downloaded your module and tried to compile it, but faced to the following error:

    'AppDelegate.h' file not found RNVideoPlayer.h

This error occurred in RNVideoPlayer.h and first line of that. So, how should I do? Where is the AppDelegate.h file? 

Thanks in advance

**Comment by BondGoat** [comment]
Hi @hoseinmobasher ,

Please check Header Search Paths in RNVideoPlayer, is it already added: $(SRCROOT)/../../../ios/HuntersLog -> recursive

It will help RNVideoPlayer interact with AppDelegate.h in root project.

Please try and let me know if you still find any problems.

Thanks.

**Comment by andrelimawork** [comment]
Hello BondGoat, i'm having the same issue. I've tried what you had sugested in your previous comment and i still get the error.

**Comment by BondGoat** [comment]
Hi @andrelimawork ,

Sorry, there's mistake in previous comment, it should be : $(SRCROOT)/../../../ios/[your project source]
The number of '../' depends on your folder structure, this path should point to the folder that contain your project's AppDelegate.h

For example my project is HuntersLog, the folder structure is:
HuntersLog:
- android
- ios:
  - HuntersLog.xcodeproj
  - HuntersLog:
    - AppDelegate.h (**this is the problem**)
    - AppDelegate.m
    - ...
- node_modules
  - ....
  - react-native-native-video-player:
    - ios: 
      - RNVideoPlayer.xcodeproj
      - RNVideoPlayer:
        - RNVideoPlayer.h (**this is where we call AppDelegate.h**)
        - RNVideoPlayer.m
- index.js
- ...

OK, so from above structure, in RNVideoPlayer -> BuildSettings -> Search Path -> Header Search Paths: add '$(SRCROOT)/../../../ios/HuntersLog' -> recursive

Please check your app folder structure and change the approriate path, it should be worked.

BRs.

**Comment by andrelimawork** [comment]
heheheh thanks for your time, i've figured out it myself.  It stays as help for other people with the same problem.

**Comment by trondwernerhansen** [comment]
@BondGoat You can avoid including AppDelegate.h by not using the delegate and instead fetch UIWindow like this:

UIWindow *window = [[UIApplication sharedApplication] keyWindow]
...
[window.rootViewController.view addSubview.....

**Comment by KlavierCat** [comment]
Just run into the same problem and solved it following the owner's suggestion. Uploading this image here for other people who run into the same problem:

<img width="1050" alt="screen shot 2017-06-18 at 04 05 41" src="https://user-images.githubusercontent.com/5871704/27257791-2511c914-53dc-11e7-94d0-e41f82145fcb.png">

I saw there is the path `$(SRCROOT)/../../../ios/HuntersLog` and I change `HuntersLog` into my own project's name, then it builds successfully.

**Comment by msdark** [comment]
But.. if this is a code to be shared, why the `HuntersLog` folder is hardcoded?

**Comment by BondGoat** [comment]
Hi @msdark ,

Because this code was first used for my Project, so in order to apply to yours, you need to make some update like what I've shown above, and 1 more reason is that the module use AppDelegate instance so you need to import it from the main project as "$(SRCROOT)/../../../ios/[your project here]".

Thanks.

**Comment by hungdev** [comment]
hi. I added and it can build. But after build success, it gets an error.
<img width="1296" alt="screen shot 2018-08-05 at 11 51 32 pm" src="https://user-images.githubusercontent.com/12009276/43688018-7d6a5bb0-990b-11e8-914f-ecfd88f735ff.png">
@BondGoat  @KlavierCat @andrelimawork could guys help me?
