### ISSUE TITLE
play video without choose app. is default gallery video player

### ISSUE THREAD

**Issue by sahimar90** [BondGoat/react-native-native-video-player#5]
how to play video without choose app ? is default gallery video player not vlc, google photos or anywhere. thanks :)

**Comment by BondGoat** [comment]
Hi @sahimar90 ,

I assumed this question is for Android. In this case I think we have 2 options:

1. Do it manually, whenever you select an native app to play video, there're 2 options for you to select it as the default or not (Always / Once). Ofcourse we can change it in Settings

2. Need to modify the code, as long as you know the app package id, you can update the code to open the whatever app you want to play your video. I'm sure you can easy find a lot of samples on Internet.

Let me know if you need more support.
BRs.

**Comment by pravinraut809** [comment]
I am getting the same issue , Not able to get how to remove default player
