### ISSUE TITLE
When the player opens, a black square appears

### ISSUE THREAD

**Issue by avkvak** [BondGoat/react-native-native-video-player#6]
Hi BondGoat, thanks for this stuff, but I got some problem:

When the player opens, a black square appears. Just for a moment, in top-left side,
Look like this is the player itself, but it would be great to be able to get rid of it

[demo gif link](https://cl.ly/0736083m2X47)

Thank you

**Comment by BondGoat** [comment]
Hi @avkvak ,

Sorry or late reply, I still haven't had any solution for this. 
Might need some helps from iOS experts.
