### ISSUE TITLE
Requesting fullscreen in emulator causes crash

### ISSUE THREAD

**Issue by samdoj** [BondGoat/react-native-native-video-player#7]
My app uses this component and crashes when I click the full screen icon in iOS 10.3 with resizeMode === 'cover'.

**Comment by BondGoat** [comment]
Hi @samdoj ,

The prop resizeMode does not support in this Library, the player was set to fit with device width & height.
I'm little busy right now, I may come back later and think about how to support the size prop in next version.

Thanks.
