### ISSUE TITLE
Not able to play web urls

### ISSUE THREAD

**Issue by cooolan00p** [BondGoat/react-native-native-video-player#9]
I tried to play web url using this component but ended in saying that 'Can't play video'
![screenshot_1502188427](https://user-images.githubusercontent.com/18212873/29068164-3bc7d88e-7c53-11e7-89a7-f8fad70aa5d3.png)

**Comment by BondGoat** [comment]
Hi @cooolan00p ,

Please make sure the URL contain playable video, this lib is using AVPlayer control, only support some video types like: *.mp4, *.mov,...

Sorry for late respond, so busy recently.
Thanks.
